name: Expo CI/CD

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install
 
      # Optionally, add steps for linting, code analysis, etc.

      - name: Log in to Expo
        run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      - name: Build
        run: npx eas build

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      
      - name: Update Configuration
        run: npx eas update

      - name: Submit to App Stores
        run: npx eas submit --platform android --release-channel default  # Replace android with ios if deploying to iOS
